import type { IstGate, ItpItem, Project, Punch, System } from "./types";

const T = {
  aug20: "2026-08-20T09:00:00.000Z",
  aug26: "2026-08-26T11:30:00.000Z",
  sep01: "2026-09-01T08:15:00.000Z",
  sep03: "2026-09-03T14:40:00.000Z",
  sep07: "2026-09-07T10:22:00.000Z",
  sep09: "2026-09-09T16:05:00.000Z",
  sep11: "2026-09-11T09:50:00.000Z",
  sep13: "2026-09-13T13:18:00.000Z",
  sep14: "2026-09-14T07:40:00.000Z",
};

export const SEED_NANTONG: Project = {
  id: "prj_nantong",
  name: "Nantong Cogen — Cx Phase",
  site: "Nantong, Jiangsu · 2× F-class GT + HRSG + STG",
  client: "FQE Power",
  vertical: "power_plant",
  status: "active",
  createdAt: T.aug20,
  updatedAt: T.sep14,
};

export const SEED_NANTONG_SYSTEMS: System[] = [
  {
    id: "sys_nt_gt1",
    projectId: SEED_NANTONG.id,
    name: "Gas turbine 1",
    tag: "GT-1",
    discipline: "Electrical",
    status: "in_test",
    createdAt: T.aug20,
    updatedAt: T.sep13,
  },
  {
    id: "sys_nt_hrsg1",
    projectId: SEED_NANTONG.id,
    name: "Heat recovery steam generator 1",
    tag: "HRSG-1",
    discipline: "Mechanical",
    status: "punch",
    createdAt: T.aug20,
    updatedAt: T.sep14,
  },
  {
    id: "sys_nt_stg1",
    projectId: SEED_NANTONG.id,
    name: "Steam turbine generator 1",
    tag: "STG-1",
    discipline: "Electrical",
    status: "in_test",
    createdAt: T.aug26,
    updatedAt: T.sep13,
  },
  {
    id: "sys_nt_swgr",
    projectId: SEED_NANTONG.id,
    name: "13.8 kV generator switchgear",
    tag: "SWGR-13kV",
    discipline: "Electrical",
    status: "in_test",
    createdAt: T.aug20,
    updatedAt: T.sep11,
  },
  {
    id: "sys_nt_cw",
    projectId: SEED_NANTONG.id,
    name: "Circulating water / cooling tower",
    tag: "CW-1",
    discipline: "Mechanical",
    status: "punch",
    createdAt: T.aug26,
    updatedAt: T.sep13,
  },
  {
    id: "sys_nt_dcs",
    projectId: SEED_NANTONG.id,
    name: "Plant distributed control system",
    tag: "DCS",
    discipline: "Controls",
    status: "in_test",
    createdAt: T.sep01,
    updatedAt: T.sep14,
  },
];

export const SEED_NANTONG_PUNCHES: Punch[] = [
  {
    id: "pnch_nt_01",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_stg1",
    number: 1,
    title: "STG overspeed trip not proven at 110% setpoint",
    description:
      "Electronic trip simulated OK. Mechanical bolt trip not demonstrated — vendor waiting on turning-gear window.",
    severity: "A",
    status: "open",
    owner: "L. Wei (CxA)",
    dueDate: "2026-09-18",
    evidenceNotes: "",
    createdAt: T.sep07,
    updatedAt: T.sep13,
    closedAt: null,
  },
  {
    id: "pnch_nt_02",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_hrsg1",
    number: 2,
    title: "Drum level transmitters disagree > 80 mm",
    description: "LT-101A vs LT-101B split after wet calibration. Cannot release boiler for firing.",
    severity: "A",
    status: "in_progress",
    owner: "FQE Mechanical",
    dueDate: "2026-09-16",
    evidenceNotes: "Recal started 13 Sep. Third transmitter (LT-101C) being landed.",
    createdAt: T.sep03,
    updatedAt: T.sep13,
    closedAt: null,
  },
  {
    id: "pnch_nt_03",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_gt1",
    number: 3,
    title: "Combustor inspection ports weeping on GT-1",
    description: "Soot streaks at ports 4 and 7 after 2-hour fired run. OEM to re-torque with new gaskets.",
    severity: "B",
    status: "open",
    owner: "Vendor — Siemens Energy",
    dueDate: "2026-09-20",
    evidenceNotes: "",
    createdAt: T.sep09,
    updatedAt: T.sep09,
    closedAt: null,
  },
  {
    id: "pnch_nt_04",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_cw",
    number: 4,
    title: "CW pump B inboard vibration 7.2 mm/s at design flow",
    description: "Alarm band is 5.6 mm/s. Alignment suspected after coupling swap.",
    severity: "B",
    status: "open",
    owner: "FQE Mechanical",
    dueDate: "2026-09-17",
    evidenceNotes: "",
    createdAt: T.sep11,
    updatedAt: T.sep13,
    closedAt: null,
  },
  {
    id: "pnch_nt_05",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_swgr",
    number: 5,
    title: "87B bus differential settings do not match coordination study",
    description: "Pickup 0.4 vs study 0.3. Cannot energize 13.8 kV bus until revised.",
    severity: "A",
    status: "open",
    owner: "FQE Electrical",
    dueDate: "2026-09-15",
    evidenceNotes: "",
    createdAt: T.sep01,
    updatedAt: T.sep11,
    closedAt: null,
  },
  {
    id: "pnch_nt_06",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_dcs",
    number: 6,
    title: "Islanding sequence of operations incomplete in DCS",
    description: "Load-rejection SAMA missing breaker fail and house-load pickup. Logic freeze requested.",
    severity: "B",
    status: "in_progress",
    owner: "Vendor — ABB",
    dueDate: "2026-09-19",
    evidenceNotes: "Cause-and-effect matrix issued 13 Sep. Waiting factory download.",
    createdAt: T.sep07,
    updatedAt: T.sep13,
    closedAt: null,
  },
  {
    id: "pnch_nt_07",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_stg1",
    number: 7,
    title: "LOTO isolation points not tagged on STG extraction steam",
    description: "Three valves on extraction line have no lock hasps. Energization permit blocked.",
    severity: "A",
    status: "open",
    owner: "L. Wei (CxA)",
    dueDate: "2026-09-14",
    evidenceNotes: "",
    createdAt: T.sep11,
    updatedAt: T.sep14,
    closedAt: null,
  },
  {
    id: "pnch_nt_08",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_gt1",
    number: 8,
    title: "Fuel-gas strainer DP not alarmed to DCS",
    description: "Local gauge only. High DP will not trip or alarm in CCR.",
    severity: "B",
    status: "closed",
    owner: "Vendor — ABB",
    dueDate: "2026-09-08",
    evidenceNotes:
      "AI point FG-DP-01 landed, alarm at 8 kPa, trip inhibit documented. Screenshot in evidence. Witnessed Wei + DCS 9 Sep.",
    createdAt: T.sep01,
    updatedAt: T.sep09,
    closedAt: T.sep09,
  },
  {
    id: "pnch_nt_09",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_swgr",
    number: 9,
    title: "GSU nitrogen blanket pressure low (28 kPa vs 40 kPa)",
    description: "Conservator bladder suspected. Not blocking 13.8 kV as long as Buchholz is in service.",
    severity: "C",
    status: "open",
    owner: "FQE Electrical",
    dueDate: "2026-09-22",
    evidenceNotes: "",
    createdAt: T.sep13,
    updatedAt: T.sep13,
    closedAt: null,
  },
  {
    id: "pnch_nt_10",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_hrsg1",
    number: 10,
    title: "Continuous blowdown silencer packing missing",
    description: "Empty canister as-shipped. Noise/steam hazard if lined up.",
    severity: "C",
    status: "closed",
    owner: "FQE Mechanical",
    dueDate: "2026-09-05",
    evidenceNotes: "Packing installed 7 Sep. Photo of filled canister filed. Lined up on recirculation — quiet.",
    createdAt: T.aug26,
    updatedAt: T.sep07,
    closedAt: T.sep07,
  },
  {
    id: "pnch_nt_11",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_swgr",
    number: 11,
    title: "Sync-check relay window too wide (20° vs specified 10°)",
    description: "Live-bus close could exceed machine stress limits. Must retune before first sync.",
    severity: "A",
    status: "in_progress",
    owner: "Vendor — Siemens Energy",
    dueDate: "2026-09-16",
    evidenceNotes: "Settings file drafted. Outage on 25 kV side booked 16 Sep night.",
    createdAt: T.sep11,
    updatedAt: T.sep14,
    closedAt: null,
  },
  {
    id: "pnch_nt_12",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_cw",
    number: 12,
    title: "Cooling tower fan 3 VFD not communicating on Modbus",
    description: "Local keypad runs. DCS shows comms fail. Cannot auto-stage fans.",
    severity: "B",
    status: "open",
    owner: "Vendor — ABB",
    dueDate: "2026-09-21",
    evidenceNotes: "",
    createdAt: T.sep13,
    updatedAt: T.sep13,
    closedAt: null,
  },
];

export const SEED_NANTONG_ITP: ItpItem[] = [
  {
    id: "itp_nt_01",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_gt1",
    stepNumber: 1,
    title: "First-fire / purge sequence",
    procedureRef: "ITP-GT-01",
    result: "pass",
    notes: "Purge timers verified. First fire 9 Sep — ports leaking (CX-003).",
    createdAt: T.sep09,
    updatedAt: T.sep09,
  },
  {
    id: "itp_nt_02",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_stg1",
    stepNumber: 1,
    title: "Overspeed trip (electronic + mechanical)",
    procedureRef: "ITP-STG-02",
    result: "fail",
    notes: "Mechanical bolt not proven. CX-001.",
    createdAt: T.sep07,
    updatedAt: T.sep13,
  },
  {
    id: "itp_nt_03",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_hrsg1",
    stepNumber: 1,
    title: "Safety valve pop / reseat",
    procedureRef: "ITP-HRSG-03",
    result: "pending",
    notes: "Waiting drum-level punch CX-002 before firing.",
    createdAt: T.sep03,
    updatedAt: T.sep13,
  },
  {
    id: "itp_nt_04",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_swgr",
    stepNumber: 1,
    title: "Sync-check dead-bus / live-bus",
    procedureRef: "ITP-SWGR-04",
    result: "pending",
    notes: "Window too wide — CX-011.",
    createdAt: T.sep11,
    updatedAt: T.sep14,
  },
  {
    id: "itp_nt_05",
    projectId: SEED_NANTONG.id,
    systemId: "sys_nt_dcs",
    stepNumber: 1,
    title: "Islanding / house-load pickup FAT vs site",
    procedureRef: "ITP-DCS-05",
    result: "pending",
    notes: "Logic incomplete. CX-006.",
    createdAt: T.sep07,
    updatedAt: T.sep13,
  },
];

export const SEED_IST_NANTONG: IstGate[] = [
  {
    id: "ist_nt_01",
    projectId: SEED_NANTONG.id,
    stepNumber: 1,
    title: "LOTO clear — extraction steam and 13.8 kV cubicles",
    result: "fail",
    notes: "STG extraction valves untagged. CX-007.",
    createdAt: T.sep11,
    updatedAt: T.sep14,
  },
  {
    id: "ist_nt_02",
    projectId: SEED_NANTONG.id,
    stepNumber: 2,
    title: "Protective relays tested (87B / 87T / 50/51)",
    result: "pending",
    notes: "87B settings mismatch. CX-005.",
    createdAt: T.sep01,
    updatedAt: T.sep11,
  },
  {
    id: "ist_nt_03",
    projectId: SEED_NANTONG.id,
    stepNumber: 3,
    title: "Sync-check relays (dead-bus / live-bus)",
    result: "fail",
    notes: "Window 20° vs 10°. CX-011.",
    createdAt: T.sep11,
    updatedAt: T.sep14,
  },
  {
    id: "ist_nt_04",
    projectId: SEED_NANTONG.id,
    stepNumber: 4,
    title: "Turbine overspeed trip proven",
    result: "fail",
    notes: "Mechanical bolt not demonstrated. CX-001.",
    createdAt: T.sep07,
    updatedAt: T.sep13,
  },
  {
    id: "ist_nt_05",
    projectId: SEED_NANTONG.id,
    stepNumber: 5,
    title: "HRSG safety valves set and tagged",
    result: "pending",
    notes: "Cannot fire until drum level CX-002 clears.",
    createdAt: T.sep03,
    updatedAt: T.sep13,
  },
  {
    id: "ist_nt_06",
    projectId: SEED_NANTONG.id,
    stepNumber: 6,
    title: "Fuel-gas ESD proven to CCR",
    result: "pass",
    notes: "Trip from CCR closed ESD-1 in 1.4 s. Witnessed 9 Sep.",
    createdAt: T.sep09,
    updatedAt: T.sep09,
  },
  {
    id: "ist_nt_07",
    projectId: SEED_NANTONG.id,
    stepNumber: 7,
    title: "Islanding / load rejection sequence",
    result: "pending",
    notes: "DCS logic incomplete. CX-006.",
    createdAt: T.sep07,
    updatedAt: T.sep13,
  },
  {
    id: "ist_nt_08",
    projectId: SEED_NANTONG.id,
    stepNumber: 8,
    title: "Grid interconnect permission / dispatch notice",
    result: "pending",
    notes: "Paperwork with grid co. First sync not scheduled.",
    createdAt: T.sep14,
    updatedAt: T.sep14,
  },
];

export const SEED_NANTONG_PHOTOS: { id: string; punchId: string; originalName: string; caption: string; stamp: string }[] = [
  {
    id: "ev_nt_08",
    punchId: "pnch_nt_08",
    originalName: "NT-008-fuel-gas-dp.svg",
    caption: "GT-1 fuel-gas strainer DP — DCS alarm FG-DP-01 live",
    stamp: "9 Sep 2026 · Wei + ABB",
  },
  {
    id: "ev_nt_10",
    punchId: "pnch_nt_10",
    originalName: "NT-010-blowdown-silencer.svg",
    caption: "HRSG-1 continuous blowdown silencer — packing installed",
    stamp: "7 Sep 2026 · FQE Mechanical",
  },
];
