import type { IstGate, ItpItem, Project, Punch, System } from "./types";

const T = {
  aug12: "2026-08-12T13:20:00.000Z",
  aug18: "2026-08-18T15:04:00.000Z",
  aug22: "2026-08-22T09:11:00.000Z",
  aug28: "2026-08-28T16:40:00.000Z",
  sep02: "2026-09-02T10:05:00.000Z",
  sep04: "2026-09-04T14:22:00.000Z",
  sep05: "2026-09-05T16:20:00.000Z",
  sep06: "2026-09-06T11:48:00.000Z",
  sep08: "2026-09-08T08:30:00.000Z",
  sep09: "2026-09-09T17:15:00.000Z",
  sep10: "2026-09-10T12:00:00.000Z",
  sep11: "2026-09-11T09:40:00.000Z",
  sep12: "2026-09-12T15:55:00.000Z",
  sep13: "2026-09-13T18:10:00.000Z",
  sep14: "2026-09-14T08:05:00.000Z",
};

export const SEED_PROJECT: Project = {
  id: "prj_columbiana",
  name: "Columbiana DC — Cx Phase",
  site: "Columbiana, OH · Hall A / 30 MW",
  client: "DataQuestCX",
  vertical: "data_center",
  status: "active",
  createdAt: T.aug12,
  updatedAt: T.sep14,
};

export const SEED_SYSTEMS: System[] = [
  {
    id: "sys_ups_a",
    projectId: SEED_PROJECT.id,
    name: "Uninterruptible Power Supply A",
    tag: "UPS-A",
    discipline: "Electrical",
    status: "in_test",
    createdAt: T.aug12,
    updatedAt: T.sep13,
  },
  {
    id: "sys_ups_b",
    projectId: SEED_PROJECT.id,
    name: "Uninterruptible Power Supply B",
    tag: "UPS-B",
    discipline: "Electrical",
    status: "in_test",
    createdAt: T.aug12,
    updatedAt: T.sep12,
  },
  {
    id: "sys_crah_01",
    projectId: SEED_PROJECT.id,
    name: "Computer Room Air Handler 01",
    tag: "CRAH-01",
    discipline: "Mechanical",
    status: "punch",
    createdAt: T.aug18,
    updatedAt: T.sep14,
  },
  {
    id: "sys_crah_02",
    projectId: SEED_PROJECT.id,
    name: "Computer Room Air Handler 02",
    tag: "CRAH-02",
    discipline: "Mechanical",
    status: "in_test",
    createdAt: T.aug18,
    updatedAt: T.sep11,
  },
  {
    id: "sys_crah_03",
    projectId: SEED_PROJECT.id,
    name: "Computer Room Air Handler 03",
    tag: "CRAH-03",
    discipline: "Mechanical",
    status: "not_started",
    createdAt: T.aug18,
    updatedAt: T.sep04,
  },
  {
    id: "sys_mdp",
    projectId: SEED_PROJECT.id,
    name: "Main Distribution Switchgear",
    tag: "Switchgear-MDP",
    discipline: "Electrical",
    status: "in_test",
    createdAt: T.aug12,
    updatedAt: T.sep13,
  },
  {
    id: "sys_gen_1",
    projectId: SEED_PROJECT.id,
    name: "Standby Generator 1",
    tag: "Generator-1",
    discipline: "Electrical",
    status: "punch",
    createdAt: T.aug22,
    updatedAt: T.sep14,
  },
  {
    id: "sys_bms",
    projectId: SEED_PROJECT.id,
    name: "Building Management System",
    tag: "BMS",
    discipline: "Controls",
    status: "in_test",
    createdAt: T.aug28,
    updatedAt: T.sep12,
  },
];

export const SEED_PUNCHES: Punch[] = [
  {
    id: "pnch_001",
    projectId: SEED_PROJECT.id,
    systemId: "sys_ups_a",
    number: 1,
    title: "Static bypass failed to transfer on simulated inverter loss",
    description:
      "During UPS-A FPT, loss-of-inverter simulation did not transfer load to static bypass within 4 ms. Load dropped for ~40 ms. Vertiv on-site 15 Sep.",
    severity: "A",
    status: "open",
    owner: "M. Chen (CxA)",
    dueDate: "2026-09-16",
    evidenceNotes: "",
    createdAt: T.sep08,
    updatedAt: T.sep13,
    closedAt: null,
  },
  {
    id: "pnch_002",
    projectId: SEED_PROJECT.id,
    systemId: "sys_ups_a",
    number: 2,
    title: "Battery cabinet B-2 missing nameplate / as-built tag",
    description: "Cabinet B-2 has no factory nameplate. Photo requested for closeout binder.",
    severity: "C",
    status: "closed",
    owner: "J. Patel (Electrical)",
    dueDate: "2026-09-05",
    evidenceNotes:
      "Vertiv shipped replacement nameplate. Photo CX-002-close.jpg filed 8 Sep. As-built markup uploaded to job folder.",
    createdAt: T.aug28,
    updatedAt: T.sep08,
    closedAt: T.sep08,
  },
  {
    id: "pnch_003",
    projectId: SEED_PROJECT.id,
    systemId: "sys_ups_b",
    number: 3,
    title: "Battery string voltage imbalance exceeds 2%",
    description: "String B2 vs B1 delta 2.7% at float. Vendor performing individual jar readings.",
    severity: "B",
    status: "in_progress",
    owner: "Vendor — Vertiv",
    dueDate: "2026-09-18",
    evidenceNotes: "Jar readings started 12 Sep. Three jars flagged for replacement.",
    createdAt: T.sep04,
    updatedAt: T.sep12,
    closedAt: null,
  },
  {
    id: "pnch_004",
    projectId: SEED_PROJECT.id,
    systemId: "sys_crah_01",
    number: 4,
    title: "Condensate drain not trapped; no air gap at floor sink",
    description: "CRAH-01 drain is hard-piped with no trap. Risk of sewer gas and overflow on loss of prime.",
    severity: "B",
    status: "open",
    owner: "R. Okonkwo (Mechanical)",
    dueDate: "2026-09-12",
    evidenceNotes: "",
    createdAt: T.sep02,
    updatedAt: T.sep10,
    closedAt: null,
  },
  {
    id: "pnch_005",
    projectId: SEED_PROJECT.id,
    systemId: "sys_crah_01",
    number: 5,
    title: "Failed to hold 72°F ±2°F at design load",
    description:
      "FPT at 80% simulated IT load: supply air drifted to 76.4°F after 22 min. Suspect undercharged circuit / dirty filter combination.",
    severity: "A",
    status: "open",
    owner: "R. Okonkwo (Mechanical)",
    dueDate: "2026-09-15",
    evidenceNotes: "",
    createdAt: T.sep10,
    updatedAt: T.sep14,
    closedAt: null,
  },
  {
    id: "pnch_006",
    projectId: SEED_PROJECT.id,
    systemId: "sys_crah_02",
    number: 6,
    title: "Filter DP sensor polarity inverted vs BAS",
    description: "BAS shows negative DP when filters are dirty. Controls to reverse scaling; re-verify against magnehelic.",
    severity: "B",
    status: "in_progress",
    owner: "S. Alvarez (Controls)",
    dueDate: "2026-09-17",
    evidenceNotes: "Point remap issued 13 Sep. Waiting night-shift download window.",
    createdAt: T.sep06,
    updatedAt: T.sep13,
    closedAt: null,
  },
  {
    id: "pnch_007",
    projectId: SEED_PROJECT.id,
    systemId: "sys_crah_03",
    number: 7,
    title: "Isolation damper actuator not powered",
    description: "24 VAC missing at actuator. Circuit 14 in CRAH-03 local panel is open. Cannot start PFC.",
    severity: "B",
    status: "open",
    owner: "J. Patel (Electrical)",
    dueDate: "2026-09-19",
    evidenceNotes: "",
    createdAt: T.sep04,
    updatedAt: T.sep04,
    closedAt: null,
  },
  {
    id: "pnch_008",
    projectId: SEED_PROJECT.id,
    systemId: "sys_mdp",
    number: 8,
    title: "Arc-flash labels missing on cubicles 3–7",
    description: "Coordination study issued 1 Sep. Labels not applied. AHJ will not sign IST without them.",
    severity: "A",
    status: "open",
    owner: "M. Chen (CxA)",
    dueDate: "2026-09-11",
    evidenceNotes: "",
    createdAt: T.sep02,
    updatedAt: T.sep11,
    closedAt: null,
  },
  {
    id: "pnch_009",
    projectId: SEED_PROJECT.id,
    systemId: "sys_mdp",
    number: 9,
    title: "Breaker 52-M1 trip settings do not match coordination study",
    description: "LTPU set 0.9 vs study 0.8; STPU 5 vs 4. Relays to be reprogrammed before secondary injection sign-off.",
    severity: "A",
    status: "in_progress",
    owner: "Vendor — Eaton",
    dueDate: "2026-09-16",
    evidenceNotes: "Settings file received. Outage window booked 15 Sep 22:00.",
    createdAt: T.sep06,
    updatedAt: T.sep12,
    closedAt: null,
  },
  {
    id: "pnch_010",
    projectId: SEED_PROJECT.id,
    systemId: "sys_gen_1",
    number: 10,
    title: "ATS failed to transfer on loss of utility (test #2)",
    description:
      "First transfer OK. Second black-start: ATS remained on utility for 18 s, then transferred. Suspect timer / sense wiring.",
    severity: "A",
    status: "open",
    owner: "Vendor — Cummins",
    dueDate: "2026-09-15",
    evidenceNotes: "",
    createdAt: T.sep11,
    updatedAt: T.sep14,
    closedAt: null,
  },
  {
    id: "pnch_011",
    projectId: SEED_PROJECT.id,
    systemId: "sys_gen_1",
    number: 11,
    title: "Fuel polish alarm not mapped to BMS",
    description: "Local panel alarm works. No BMS point; will not annunciate in NOC.",
    severity: "B",
    status: "open",
    owner: "S. Alvarez (Controls)",
    dueDate: "2026-09-20",
    evidenceNotes: "",
    createdAt: T.sep09,
    updatedAt: T.sep09,
    closedAt: null,
  },
  {
    id: "pnch_012",
    projectId: SEED_PROJECT.id,
    systemId: "sys_gen_1",
    number: 12,
    title: "Exhaust flex connection weeping at flange",
    description: "Light soot stain at flex-to-silencer flange after 30-min run.",
    severity: "C",
    status: "closed",
    owner: "Vendor — Cummins",
    dueDate: "2026-09-08",
    evidenceNotes:
      "Gasket replaced 9 Sep. Re-ran 20 min — dry. Photo CX-012-close.jpg in evidence folder.",
    createdAt: T.aug22,
    updatedAt: T.sep09,
    closedAt: T.sep09,
  },
  {
    id: "pnch_013",
    projectId: SEED_PROJECT.id,
    systemId: "sys_bms",
    number: 13,
    title: "Point list incomplete vs as-built for CRAH-03",
    description: "47 of 62 points present. Missing valve positions, filter DP, and leak detect.",
    severity: "B",
    status: "open",
    owner: "S. Alvarez (Controls)",
    dueDate: "2026-09-22",
    evidenceNotes: "",
    createdAt: T.sep08,
    updatedAt: T.sep12,
    closedAt: null,
  },
  {
    id: "pnch_014",
    projectId: SEED_PROJECT.id,
    systemId: "sys_bms",
    number: 14,
    title: "Time sync drift vs GPS clock > 5 s",
    description: "Historian timestamps drifting; trend overlays unusable for IST.",
    severity: "C",
    status: "closed",
    owner: "S. Alvarez (Controls)",
    dueDate: "2026-09-06",
    evidenceNotes:
      "NTP pointed at GPS clock 10.20.4.8. Drift now < 200 ms over 12 h. Screenshot of clock page attached.",
    createdAt: T.aug28,
    updatedAt: T.sep06,
    closedAt: T.sep06,
  },
  {
    id: "pnch_015",
    projectId: SEED_PROJECT.id,
    systemId: "sys_ups_a",
    number: 15,
    title: "EPO not tested with AHJ present",
    description: "Owner will not allow EPO live test until AHJ + Vertiv + CxA on site. Scheduled 18 Sep.",
    severity: "A",
    status: "open",
    owner: "M. Chen (CxA)",
    dueDate: "2026-09-18",
    evidenceNotes: "",
    createdAt: T.sep10,
    updatedAt: T.sep10,
    closedAt: null,
  },
  {
    id: "pnch_016",
    projectId: SEED_PROJECT.id,
    systemId: "sys_crah_02",
    number: 16,
    title: "Vibration isolators not grouted",
    description: "Housekeeping pads poured; isolators sitting free. TAB postponed.",
    severity: "C",
    status: "closed",
    owner: "R. Okonkwo (Mechanical)",
    dueDate: "2026-09-04",
    evidenceNotes: "Grout complete 5 Sep. Photos of all four isolators filed. TAB booked 16 Sep.",
    createdAt: T.aug18,
    updatedAt: T.sep05,
    closedAt: "2026-09-05T16:20:00.000Z",
  },
  {
    id: "pnch_017",
    projectId: SEED_PROJECT.id,
    systemId: "sys_mdp",
    number: 17,
    title: "Spare 400A breaker shipped with incorrect trip unit",
    description: "Specified 400A LSI; received 600A LI. Held in warehouse, not installed.",
    severity: "B",
    status: "closed",
    owner: "J. Patel (Electrical)",
    dueDate: "2026-09-10",
    evidenceNotes:
      "Correct trip unit received 11 Sep (packing slip PS-4419). Installed, torque verified 48 ft-lb. IR scan clean.",
    createdAt: T.aug22,
    updatedAt: T.sep11,
    closedAt: T.sep11,
  },
  {
    id: "pnch_018",
    projectId: SEED_PROJECT.id,
    systemId: "sys_ups_b",
    number: 18,
    title: "IR scan: 18K hotspot on output bus connection",
    description: "Phase B output lug 18K above adjacent phases at 70% load. Re-torque and re-scan required before IST.",
    severity: "A",
    status: "in_progress",
    owner: "J. Patel (Electrical)",
    dueDate: "2026-09-14",
    evidenceNotes: "Outage requested. Thermal image IR-UPSB-18 in evidence folder.",
    createdAt: T.sep12,
    updatedAt: T.sep13,
    closedAt: null,
  },
  {
    id: "pnch_019",
    projectId: SEED_PROJECT.id,
    systemId: "sys_bms",
    number: 19,
    title: "Generator-1 graphic shows stale run hours",
    description: "Graphic frozen at 41.2 h; local panel reads 46.8 h. Binding issue on analog input.",
    severity: "C",
    status: "open",
    owner: "S. Alvarez (Controls)",
    dueDate: "2026-09-21",
    evidenceNotes: "",
    createdAt: T.sep12,
    updatedAt: T.sep12,
    closedAt: null,
  },
  {
    id: "pnch_020",
    projectId: SEED_PROJECT.id,
    systemId: "sys_crah_01",
    number: 20,
    title: "Access panel interlock not wired",
    description: "Door switch present, not landed. Unit can run with panel open — safety punch from CxA walkdown.",
    severity: "B",
    status: "closed",
    owner: "J. Patel (Electrical)",
    dueDate: "2026-09-09",
    evidenceNotes:
      "Landed on TB-2 / 7-8. Continuity + functional: opening panel trips unit and alarms BMS. Video clip on job phone uploaded.",
    createdAt: T.sep02,
    updatedAt: T.sep09,
    closedAt: T.sep09,
  },
];

export const SEED_ITP: ItpItem[] = [
  {
    id: "itp_01",
    projectId: SEED_PROJECT.id,
    systemId: "sys_ups_a",
    stepNumber: 1,
    title: "Pre-functional checklist (PFC) complete",
    procedureRef: "ITP-UPS-01",
    result: "pass",
    notes: "PFC signed 4 Sep. Two C-punches only; none blocking.",
    createdAt: T.aug28,
    updatedAt: T.sep04,
  },
  {
    id: "itp_02",
    projectId: SEED_PROJECT.id,
    systemId: "sys_ups_a",
    stepNumber: 2,
    title: "Factory witness / FAT package received",
    procedureRef: "ITP-UPS-02",
    result: "pass",
    notes: "FAT binder in trailer. Serials match nameplates.",
    createdAt: T.aug12,
    updatedAt: T.aug18,
  },
  {
    id: "itp_03",
    projectId: SEED_PROJECT.id,
    systemId: "sys_ups_a",
    stepNumber: 3,
    title: "Load-bank test 0 / 50 / 100%",
    procedureRef: "ITP-UPS-03 / FPT-04",
    result: "fail",
    notes: "100% aborted — static bypass punch CX-001. Retest after vendor fix.",
    createdAt: T.sep08,
    updatedAt: T.sep08,
  },
  {
    id: "itp_04",
    projectId: SEED_PROJECT.id,
    systemId: "sys_ups_b",
    stepNumber: 1,
    title: "Battery discharge test",
    procedureRef: "ITP-UPS-04",
    result: "pending",
    notes: "On hold until string imbalance CX-003 cleared.",
    createdAt: T.sep04,
    updatedAt: T.sep12,
  },
  {
    id: "itp_05",
    projectId: SEED_PROJECT.id,
    systemId: "sys_crah_01",
    stepNumber: 1,
    title: "Air balance / TAB",
    procedureRef: "ITP-MECH-01",
    result: "pending",
    notes: "Cannot TAB until SAT punch CX-005 resolved.",
    createdAt: T.sep02,
    updatedAt: T.sep10,
  },
  {
    id: "itp_06",
    projectId: SEED_PROJECT.id,
    systemId: "sys_crah_01",
    stepNumber: 2,
    title: "Functional performance test (FPT)",
    procedureRef: "ITP-MECH-02",
    result: "fail",
    notes: "Failed SAT band. See CX-005.",
    createdAt: T.sep10,
    updatedAt: T.sep10,
  },
  {
    id: "itp_07",
    projectId: SEED_PROJECT.id,
    systemId: "sys_crah_02",
    stepNumber: 1,
    title: "Functional performance test (FPT)",
    procedureRef: "ITP-MECH-02",
    result: "pending",
    notes: "Scheduled 16 Sep after grout closeout.",
    createdAt: T.sep05,
    updatedAt: T.sep11,
  },
  {
    id: "itp_08",
    projectId: SEED_PROJECT.id,
    systemId: "sys_mdp",
    stepNumber: 1,
    title: "Torque verification (as-left)",
    procedureRef: "ITP-SWG-01",
    result: "pass",
    notes: "Torque sheet signed 11 Sep. Spot-check 12 lugs.",
    createdAt: T.sep06,
    updatedAt: T.sep11,
  },
  {
    id: "itp_09",
    projectId: SEED_PROJECT.id,
    systemId: "sys_mdp",
    stepNumber: 2,
    title: "Protective relay secondary injection",
    procedureRef: "ITP-SWG-02",
    result: "pending",
    notes: "Waiting CX-009 settings correction.",
    createdAt: T.sep06,
    updatedAt: T.sep12,
  },
  {
    id: "itp_10",
    projectId: SEED_PROJECT.id,
    systemId: "sys_gen_1",
    stepNumber: 1,
    title: "4-hour load-bank run",
    procedureRef: "ITP-GEN-01",
    result: "pass",
    notes: "4.1 h at 80% — temps/fuel OK. ATS still open punch.",
    createdAt: T.sep09,
    updatedAt: T.sep09,
  },
  {
    id: "itp_11",
    projectId: SEED_PROJECT.id,
    systemId: "sys_gen_1",
    stepNumber: 2,
    title: "ATS sequence of operations",
    procedureRef: "ITP-GEN-02",
    result: "fail",
    notes: "Test #2 failed. CX-010. Cummins returning 15 Sep.",
    createdAt: T.sep11,
    updatedAt: T.sep11,
  },
  {
    id: "itp_12",
    projectId: SEED_PROJECT.id,
    systemId: "sys_bms",
    stepNumber: 1,
    title: "Point-to-point verification",
    procedureRef: "ITP-BMS-01",
    result: "pending",
    notes: "CRAH-03 points incomplete (CX-013).",
    createdAt: T.sep08,
    updatedAt: T.sep12,
  },
  {
    id: "itp_13",
    projectId: SEED_PROJECT.id,
    systemId: "sys_bms",
    stepNumber: 2,
    title: "Alarm annunciation / NOC test",
    procedureRef: "ITP-BMS-02",
    result: "na",
    notes: "NOC circuit not turned over. Deferred to IST week.",
    createdAt: T.sep12,
    updatedAt: T.sep12,
  },
  {
    id: "itp_14",
    projectId: SEED_PROJECT.id,
    systemId: "sys_ups_a",
    stepNumber: 4,
    title: "Integrated systems test (IST) readiness gate",
    procedureRef: "ITP-IST-01",
    result: "pending",
    notes: "Blocked on A-punches CX-001, CX-008, CX-010, CX-015.",
    createdAt: T.sep14,
    updatedAt: T.sep14,
  },
];

export const SEED_IST_COLUMBIANA: IstGate[] = [
  {
    id: "ist_col_01",
    projectId: SEED_PROJECT.id,
    stepNumber: 1,
    title: "LOTO clear — isolation points restored, permits closed",
    result: "pass",
    notes: "CxA walkdown 12 Sep. Two leftover locks on CRAH-03 cleared.",
    createdAt: T.sep12,
    updatedAt: T.sep12,
  },
  {
    id: "ist_col_02",
    projectId: SEED_PROJECT.id,
    stepNumber: 2,
    title: "Protective relays tested (secondary injection)",
    result: "pending",
    notes: "Blocked on CX-009 trip settings. Eaton outage 15 Sep.",
    createdAt: T.sep06,
    updatedAt: T.sep12,
  },
  {
    id: "ist_col_03",
    projectId: SEED_PROJECT.id,
    stepNumber: 3,
    title: "Arc-flash labels applied on MDP cubicles",
    result: "fail",
    notes: "CX-008. AHJ will not witness IST without labels.",
    createdAt: T.sep02,
    updatedAt: T.sep11,
  },
  {
    id: "ist_col_04",
    projectId: SEED_PROJECT.id,
    stepNumber: 4,
    title: "UPS static bypass proven under inverter loss",
    result: "fail",
    notes: "CX-001. Vertiv on-site 15 Sep.",
    createdAt: T.sep08,
    updatedAt: T.sep13,
  },
  {
    id: "ist_col_05",
    projectId: SEED_PROJECT.id,
    stepNumber: 5,
    title: "Generator ATS sequence of operations proven",
    result: "fail",
    notes: "Test #2 failed. CX-010.",
    createdAt: T.sep11,
    updatedAt: T.sep14,
  },
  {
    id: "ist_col_06",
    projectId: SEED_PROJECT.id,
    stepNumber: 6,
    title: "EPO tested with AHJ present",
    result: "pending",
    notes: "Scheduled 18 Sep. CX-015.",
    createdAt: T.sep10,
    updatedAt: T.sep10,
  },
  {
    id: "ist_col_07",
    projectId: SEED_PROJECT.id,
    stepNumber: 7,
    title: "BMS critical alarms annunciate at NOC",
    result: "pending",
    notes: "NOC circuit not turned over. ITP-BMS-02 N/A.",
    createdAt: T.sep12,
    updatedAt: T.sep12,
  },
  {
    id: "ist_col_08",
    projectId: SEED_PROJECT.id,
    stepNumber: 8,
    title: "IST script / hold points approved by owner Cx",
    result: "pending",
    notes: "Draft in review. Cannot run until A-punches clear.",
    createdAt: T.sep14,
    updatedAt: T.sep14,
  },
];

export const SEED_EVIDENCE_PHOTOS: { id: string; punchId: string; originalName: string; caption: string; stamp: string }[] = [
  {
    id: "ev_pnch002",
    punchId: "pnch_002",
    originalName: "CX-002-nameplate.svg",
    caption: "UPS-A battery cabinet B-2 — replacement nameplate installed",
    stamp: "8 Sep 2026 · J. Patel",
  },
  {
    id: "ev_pnch012",
    punchId: "pnch_012",
    originalName: "CX-012-exhaust-flange.svg",
    caption: "Generator-1 exhaust flex — dry after gasket swap",
    stamp: "9 Sep 2026 · Cummins",
  },
  {
    id: "ev_pnch017",
    punchId: "pnch_017",
    originalName: "CX-017-trip-unit.svg",
    caption: "MDP spare 400A — correct LSI trip unit, torque 48 ft-lb",
    stamp: "11 Sep 2026 · IR scan clean",
  },
];
